language: bash

addons:
  apt:
    update: true

services:
  - docker

install:
  - docker build --tag postgres-plperl-server .
  - docker run --detach --publish 5432:5432 --name postgres-plperl-server postgres-plperl-server

script:
  - until docker exec postgres-plperl-server pg_isready; do sleep 1; done
  - docker exec postgres-plperl-server psql -U postgres -c "CREATE EXTENSION plperl;"
  - docker exec postgres-plperl-server psql -U postgres -c "CREATE EXTENSION plperlu;"
