language: bash

services:
  - docker

install:
  - docker build -t postgres-plperl-server .
  - docker run -d -p 5432:5432 --name postgres-plperl-server postgres-plperl-server

script:
  - docker exec postgres-plperl-server psql -U postgres -c "SELECT CURRENT_TIMESTAMP;"
