language: bash

addons:
  apt:
    update: true

services:
  - docker

install:
  - docker build -t postgres-plperl-server .
  - docker run -d -p 5432:5432 --name postgres-plperl-server postgres-plperl-server

script:
  - docker ps
  - sleep 20
  - docker exec postgres-plperl-server psql -U postgres -c "SELECT NOW();"
